language: ruby
rvm:
  - rvm 2.2.5
  - rvm 2.3.0

env:
  global:
    - TWILIO_ACCOUNT_SID=AC2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - TWILIO_AUTH_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - TWILIO_NUMBER=+15551230987
